### ISSUE TITLE
address pedigree collapse

### ISSUE THREAD

**Issue by gtorkelson** [gtorkelson/gedcom-solvent#1]
Pedigree collapse within a tree isn't being picked up. In a deep tree this can result in an "explosion" of duplicates. 

In FTDNA, this can be overcome by comparing the data-id attribute on the member div.

In Gedmatch, compare the url.

**Comment by kaffy123** [comment]
After reading this a few times I understand now that you mean comparing the url after opening a family pedigree within a large tree too make sure you aren't downloading the same tree twice or more times should be done.

And where it says "comparing the data-id attribute on the member div." it means that once you expand the family pedigree within a large tree on FTDNA, so that the same people aren't downloaded again, you then compare the number at the end of the url that comes after the underscore to make sure they aren't the same?  That the number after the underscore is the id for a family pedigree within a large tree?
